
import { GoogleGenAI } from "@google/genai";

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export async function swapClothing(modelImageBase64: string, clothingImageBase64: string): Promise<string> {
  const model = 'gemini-2.5-flash-image';

  const prompt = `Take the clothing from the second image and place it realistically on the person in the first image. Maintain the person's pose and body shape. The background should be clean and simple, similar to the first image. The output should be only the edited image.`;

  const modelImagePart = {
    inlineData: {
      mimeType: 'image/jpeg',
      data: modelImageBase64,
    },
  };

  const clothingImagePart = {
    inlineData: {
      mimeType: 'image/jpeg',
      data: clothingImageBase64,
    },
  };
  
  const textPart = {
      text: prompt
  };

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [textPart, modelImagePart, clothingImagePart],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    
    throw new Error('No image was generated by the API.');

  } catch (error) {
    console.error('Error calling Gemini API:', error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate image: ${error.message}`);
    }
    throw new Error('An unknown error occurred while communicating with the Gemini API.');
  }
}
